- Jenkinsfile
- ruta-parent/pom.xml
- Added Jenkinsfile
- Tell the rat to log the names of files with bad license headers to the console since on ci-builds, we do not seem to have access to browse workspaces
> [UIMA-6260] Jenkinsfile for UIMA Ruta

- ruta-core/src/main/java/org/apache/uima/ruta/rule/ComposedRuleElement.java
- ruta-core/src/test/java/org/apache/uima/ruta/rule/ComposedRuleElementTest.java
- avoid overriding match linking: do not assign wrong element match to previous rulematch
- set direction in conjunction match
> UIMA-6324: | and & REs may miss matches

- ruta-core/src/main/java/org/apache/uima/ruta/rule/ComposedRuleElement.java
- ruta-core/src/test/java/org/apache/uima/ruta/rule/ConjunctRulesTest.java
- fix matched info for failed lookahead
> [UIMA-6344] Ruta: ConjunctRules fires without justification

- ruta-ep-ide-ui/src/main/java/org/apache/uima/ruta/ide/ui/text/RutaCodeScanner.java
- ruta-ep-ide-ui/src/main/java/org/apache/uima/ruta/ide/ui/text/RutaColorConstants.java
- use eclipse default as default token
> [UIMA-6255] Ruta: font and syntax coloring in dark mode in Ruta Workbench

- ruta-core/src/test/java/org/apache/uima/ruta/rule/WildCard2Test.java
- was already fixed, added test
> [UIMA-6309] Ruta: fallback in failed wildcard lookahead

- ruta-core/src/main/java/org/apache/uima/ruta/cache/RutaPatternCache.java
- Removed time-based clearing of the RutaPatternCache to avoid cleanup threads being spawned
- Added a way to configure the pattern cache size from a system property
> [UIMA-6399] RutaPatternCache prevents CPEEngine from terminating

- ruta-core/src/main/java/org/apache/uima/ruta/rule/WildCardRuleElement.java
- improve iterator position check
> UIMA-6409: Ruta: possible endless wildcard lookahead in combination with subtokens

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/refactoring.md
- .github/PULL_REQUEST_TEMPLATE.md
- pom.xml
- Added PR template
- Added tentative issue templates in case we switch from Jira to GitHub Issues
- Added contact links to the "new issue" page in case we switch from Jira to GitHub Issues
- Exclude templates from RAT check
> [UIMA-6433] Update issue and PR templates

- example-projects/ruta-ep-example-extensions/pom.xml
- ruta-eclipse-update-site/category.xml
- ruta-eclipse-update-site/pom.xml
- ruta-ep-addons/pom.xml
- ruta-ep-caseditor/pom.xml
- ruta-ep-core-ext/pom.xml
- ruta-ep-engine/pom.xml
- ruta-ep-ide-ui/pom.xml
- ruta-ep-ide/pom.xml
- ruta-ep-textruler/pom.xml
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6458
- Remove "finalName" from the Eclipse modules
- Update version in the Eclipse update site module
- Update to UIMA Parent POM 15-SNAPSHOT
- Set "dropPrevVersions" in the Eclipse update site module
- Changed engine bundle to not import the org.apache.uima.fit.* packages since it brings uimaFIT along and even exports its packages - without this e.g. org.apache.uima.fit.legacy would get imported which does not even exist anymore...
* Run build and {{find . -name "*parsed*"}}
<sub><sup>Only dependencies under [approved licenses](http://www.apache.org/legal/resolved.html#category-a) are allowed. LICENSE and NOTICE files in the …
> [UIMA-6458] Spurious "parsedVersion.osgiVersion" in file names in target

- ruta-core/src/main/java/org/apache/uima/ruta/resource/RutaResourceLoader.java
- Add second fallback considering the TCCL
> Issue #102 - RutaResourceLoader should consider TCCL

- ruta-basic-type/pom.xml
- ruta-core/pom.xml
- ruta-typesystem/pom.xml
- Move capabilitiy headers from type fragments to ruta-core bundle because of https://issues.apache.org/jira/browse/ARIES-2082
- Allow core bundle to resolve even if no serviceloader registrar is available
* Deploy in OSGI environment with spifly
> Issue #100: Enable type system discovery via SPI in OSGI

- ruta-core/src/main/java/org/apache/uima/ruta/action/MacroAction.java
- ruta-core/src/main/java/org/apache/uima/ruta/rule/RutaRule.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/MacroActionTest.java
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-XXXX
- changed conventions of usage
- deactivated auto labelling of all action within marco definitions
- collect inlined labels in rule preparation
- added and modified tests
* ...
> Issue #110: Usage of labels within macro action definition is broken

- ruta-eclipse-feature/feature.xml
- ruta-eclipse-update-site/category.xml
- ruta-ep-ide-ui/src/main/java/org/apache/uima/ruta/ide/debug/ui/launchConfiguration/RutaCommonTab.java
- ruta-ep-ide-ui/src/main/java/org/apache/uima/ruta/ide/ui/preferences/RutaSmartTypingConfigurationBlock.java
- ruta-ep-parent/pom.xml
- ruta-parent/pom.xml
- Switch to Eclipse 2023-09 baseline
- Force dependency on DLTK 5.11.0
- Add Eclipse 2018-12 update site as a reference repository to the Ruta feature so users can get DLTK 5.11.0 which is no longer included in recent Eclipse releases
- Replace some uses of deprecated API
* Build and try installing the result into Eclipse 2023-09
> Issue #133: Update dependencies

- ruta-core/src/main/java/org/apache/uima/ruta/rule/ComposedRuleElement.java
- ruta-core/src/test/java/org/apache/uima/ruta/rule/ComposedRuleElementWithQuantifierTest.java
- ruta-ep-engine/pom.xml
- ruta-ep-textruler/src/main/java/org/apache/uima/ruta/textruler/learner/kep/KEPPreferencePage.java
- ruta-ep-textruler/src/main/java/org/apache/uima/ruta/textruler/learner/lp2/NaiveLP2PreferencePage.java
- ruta-ep-textruler/src/main/java/org/apache/uima/ruta/textruler/learner/lp2/OptimizedLP2PreferencePage.java
- ruta-ep-textruler/src/main/java/org/apache/uima/ruta/textruler/learner/rapier/RapierPreferencePage.java
- ruta-ep-textruler/src/main/java/org/apache/uima/ruta/textruler/learner/whisk/generic/WhiskGenericPreferencePage.java
- ruta-ep-textruler/src/main/java/org/apache/uima/ruta/textruler/learner/whisk/token/WhiskTokenPreferencePage.java
- fixed rule inference
- some cleanup
* ...
> Issue #139: Unexpected behavior of plus operator

- ruta-ep-addons/src/main/java/org/apache/uima/ruta/query/ui/QueryActionHandler.java
- ruta-ep-addons/src/main/java/org/apache/uima/ruta/query/ui/QueryComposite.java
- Check for proper data location and type system location and generate error otherwise
* Try entering an invalid location into the data location field
* Try running a query without specifying a type system
> Issue #152: Better error messages in query view

- ruta-ep-core-ext/pom.xml
- ruta-ep-engine/pom.xml
- ruta-parent/pom.xml
- Make sure that ruta-ext Eclipse plugin does not export the  org.apache.uima.ruta package
- Bit of cleaning up
* See issue description
> Issue #151: Unable to use Ruta Query view in Ruta 3.4.0-RC-1

- ruta-core/src/main/java/org/apache/uima/ruta/RutaStream.java
- ruta-core/src/main/java/org/apache/uima/ruta/expression/AnnotationTypeExpression.java
- ruta-core/src/main/java/org/apache/uima/ruta/expression/RutaExpression.java
- ruta-core/src/main/java/org/apache/uima/ruta/expression/annotation/AnnotationListDelegateVariableExpression.java
- ruta-core/src/main/java/org/apache/uima/ruta/expression/annotation/AnnotationListFeatureExpression.java
- ruta-core/src/main/java/org/apache/uima/ruta/expression/annotation/AnnotationListLabelExpression.java
- ruta-core/src/main/java/org/apache/uima/ruta/expression/annotation/AnnotationListVariableExpression.java
- ruta-core/src/main/java/org/apache/uima/ruta/expression/annotation/IAnnotationListExpression.java
- ruta-core/src/main/java/org/apache/uima/ruta/expression/feature/GenericFeatureExpression.java
- ruta-core/src/main/java/org/apache/uima/ruta/expression/feature/SimpleFeatureExpression.java
- ruta-core/src/test/java/org/apache/uima/ruta/expression/annotation/AnnotationFeatureExpressionTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/expression/feature/FeatureStructureTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/expression/string/StringExpressionTest.java
Issue #170: Type based annotation assignments should only add visible annotations
Issue #171: Support implicit FSArray assigments with FeatureStructures
* added and fixed tests
* filter on visibilty when selecting annotations
* fix assignment with full namespace
* better support featre structures in lists
* ...
> Issue #169: Annotation assignment not working correctly

- pom.xml
- ruta-core/pom.xml
- ruta-documentation/pom.xml
- ruta-ep-engine/src/main/readme_bin/LICENSE
- ruta-ep-engine/src/main/readme_bin/NOTICE
- ruta-ep-ide/pom.xml
- ruta-maven-archetype/pom.xml
- ruta-parent/pom.xml
- Pin ruta-maven-plugin version to 3.4.1 because Maven does not like using a plugin that has been created in the same reactor
- antlr3-maven-plugin 3.5.2 -> 3.5.3
- tycho 4.0.4 -> 4.0.10
- commons-io 2.17.0 -> 2.18.0
- spring 5.3.39 -> 6.1.15
- asciidoctor-maven-plugin 3.1.0 -> 3.1.1
- p2-layout-resolver 1.7.0 -> 1.9.0
- maven-archetype-plugin 3.1.2 -> 3.3.1
- Removed explicit jruby dependency from asciidoc plugin
<sub><sup>Only dependencies under [approved licenses](http://www.apache.org/legal/resolved.html#category-a) are allowed. LICENSE and NOTICE files in the respective modules where dependencies have been added as well as in the project root have been …
> Issue #176: Upgrade dependencies

- ruta-core/pom.xml
- ruta-core/src/main/java/org/apache/uima/ruta/type/spi/RutaTypeSystemProvider.java
- ruta-core/src/main/resources/META-INF/services/org.apache.uima.spi.TypeSystemProvider
- Rename SPI class
- Add SPI discovery file to META-INF/services (only with the 3.6.0 SPI interface, not with the legacy interfaces)
* Try discovering types and JCas classes via SPI (requires classloader isolation)
> Issue #177: Consider resource manager when loading type descriptions

- README.md
- pom.xml
- Adding `-Ddisable-build-eclipse-plugins` will skip the Eclipse plugins during the build
* Try the option
> Issue #191: Add option to build without Eclipse plugins
