- ruta-core/src/test/java/org/apache/uima/ruta/engine/HandleDataPathTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/engine/ResourcesFromDataPathTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/engine/RutaEngineTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/engine/UimaClassLoaderTest.java
- Restore original ResourceManagerFactory after using a custom one
> [UIMA-6233] Failing unit tests depending on test execution order

- ruta-core/src/main/java/org/apache/uima/ruta/action/FillAction.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/FillTest.java
- touch all annotations in list
- added test
> UIMA-6258: Action FILL only considers first annotation of given type

- ruta-core/pom.xml
- ruta-core/src/main/java/org/apache/uima/ruta/RutaBasicUtils.java
- ruta-core/src/main/java/org/apache/uima/ruta/engine/RutaEngine.java
- ruta-core/src/test/java/org/apache/uima/ruta/RutaBasicUtilsTest.java
- ruta-docbook/src/docbook/tools.ruta.overview.xml
- ruta-parent/pom.xml
- added config param
- added utils method with tests
- added mention in docs
> UIMA-6271: Ruta: option to validate internal indexing in RutaEngine

- .gitignore
- Jenkinsfile
minor corrections in the internal indexing documentation
> HD-6268: revised and improved documentation

- .gitignore
- Jenkinsfile
- ruta-core/pom.xml
- Enabled jflex plugin in Eclipse builds
> [UIMA-6323] seed lexer not generated when building in eclipse

- ruta-core/src/main/java/org/apache/uima/ruta/seed/DefaultSeeder.java
- ruta-core/src/main/jflex/org/apache/uima/ruta/seed/SeedLexer.flex
- ruta-core/src/test/java/org/apache/uima/ruta/engine/RutaModifierTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/seed/DefaultSeederTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/seed/TextSeederTest.java
> UIMA-6319: TextSeeder creates MARKUP annotations

- ruta-core/src/main/java/org/apache/uima/ruta/engine/RutaEngine.java
> UIMA-6332: Ruta: change seeders param default to TextSeeder

- ruta-core/src/main/java/org/apache/uima/ruta/engine/RutaTestUtils.java
- ruta-core/src/main/resources/org/apache/uima/ruta/engine/BasicEngine.xml
- ruta-core/src/test/java/org/apache/uima/ruta/WSDictionaryTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/AddFilterTypeTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/AddRetainTypeTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/FilterTypeTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/MarkTableTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/RemoveFilterTypeTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/RemoveRetainTypeTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/ReplaceTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/RetainTypeTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/Shift1Test.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/Shift2Test.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/TrimTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/engine/RutaModifierTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/rule/LiteralStringMatchTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/seed/DefaultSeederTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/seed/TextSeederTest.java
- ruta-core/src/test/resources/org/apache/uima/ruta/TypeAliasTestEngine.xml
- ruta-core/src/test/resources/org/apache/uima/ruta/action/ConfigureTestEngine.xml
- ruta-core/src/test/resources/org/apache/uima/ruta/action/Shift2Test.ruta
- ruta-core/src/test/resources/org/apache/uima/ruta/action/Shift2Test.txt
- ruta-core/src/test/resources/org/apache/uima/ruta/engine/CWEngine.xml
- ruta-core/src/test/resources/org/apache/uima/ruta/engine/RecursiveConfigureEngine.xml
- ruta-core/src/test/resources/org/apache/uima/ruta/engine/SWEngine.xml
- ruta-core/src/test/resources/org/apache/uima/ruta/engine/SimpleEngine.xml
- ruta-docbook/src/docbook/tools.ruta.overview.xml
> UIMA-6332: Ruta: change seeders param default to TextSeeder Part 2

- ruta-core/src/main/java/org/apache/uima/ruta/condition/AfterCondition.java
- ruta-core/src/main/java/org/apache/uima/ruta/condition/BeforeCondition.java
- ruta-core/src/test/java/org/apache/uima/ruta/condition/AfterTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/condition/BeforeTest.java
- reimplemented BEFORE and AFTER condition
> UIMA-6340: Ruta: Condition AFTER does not respect BLOCK window

- ruta-core/src/main/java/org/apache/uima/ruta/RutaStream.java
- ruta-core/src/main/java/org/apache/uima/ruta/condition/VoteCondition.java
- ruta-core/src/test/java/org/apache/uima/ruta/condition/VoteTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/engine/DummySeeder.java
- ruta-core/src/test/java/org/apache/uima/ruta/engine/TestRutaInferenceVisitor.java
> UIMA-6338: Ruta: Inconsistency Interpreter vs. Guide on VOTE

- ruta-core-ext/src/main/java/org/apache/uima/ruta/block/fst/Automaton.java
- ruta-core/src/main/java/org/apache/uima/ruta/RutaEnvironment.java
- ruta-core/src/main/java/org/apache/uima/ruta/engine/RutaEngine.java
- ruta-core/src/test/java/org/apache/uima/ruta/TypeIgnorePatternTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/engine/DummySeeder.java
- ruta-core/src/test/java/org/apache/uima/ruta/engine/TestRutaInferenceVisitor.java
- ruta-core/src/test/java/org/apache/uima/ruta/rule/RuleInference1Test.java
- ruta-docbook/src/docbook/tools.ruta.overview.xml
- added new parameter for ignoring types
> UIMA-6343: Ruta should provide config parameters to ease type disambiguation

- ruta-ep-ide-ui/src/main/java/org/apache/uima/ruta/ide/launching/RutaLaunchConfigurationDelegate.java
java modules are not supported in simple ruta projects
> [UIMA-6213] Ruta: LayerInstantiationException in LaunchDelegate using newer Java versions

- ruta-core/src/main/antlr3/org/apache/uima/ruta/parser/RutaParser.g
- ruta-core/src/test/java/org/apache/uima/ruta/expression/annotation/AnnotationLabelExpressionTest.java
- extend boolean annotation expression grammar
> [UIMA-6247] Ruta: not able to check label expression on null as implicit condition

- ruta-core/src/main/java/org/apache/uima/ruta/RutaBasicUtils.java
> [UIMA-6345] RutaBasicUtils should not require RutaBasic type

- ruta-typesystem/src/main/resources/org/apache/uima/ruta/engine/RutaInternalTypeSystem.xml
> [UIMA-6356] Ruta: option to indentify groups of eval annotations

- ruta-core/src/main/java/org/apache/uima/ruta/engine/Ruta.java
- ruta-core/src/main/java/org/apache/uima/ruta/engine/RutaEngine.java
- ruta-core/src/main/java/org/apache/uima/ruta/expression/feature/FeatureMatchExpression.java
- ruta-core/src/main/java/org/apache/uima/ruta/expression/feature/SimpleFeatureExpression.java
- ruta-core/src/main/java/org/apache/uima/ruta/resource/MultiTreeWordList.java
- ruta-core/src/main/java/org/apache/uima/ruta/resource/TreeWordList.java
- ruta-core/src/main/java/org/apache/uima/ruta/rule/RutaAnnotationTypeMatcher.java
- ruta-core/src/main/java/org/apache/uima/ruta/utils/UIMAUtils.java
- ruta-core/src/main/java/org/apache/uima/ruta/visitor/DebugInfoCollectorVisitor.java
- ruta-core/src/main/java/org/apache/uima/ruta/visitor/DebugInfoFactory.java
- ruta-core/src/test/java/org/apache/uima/ruta/engine/RulesParamTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/engine/RutaTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/expression/annotation/AnnotationAddressExpressionTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/expression/annotation/AnnotationFeatureExpressionTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/expression/annotation/AnnotationLabelExpressionTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/expression/annotation/AnnotationVariableExpressionTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/expression/feature/FeatureStructureTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/visitor/DebugAddToIndexesTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/visitor/InlinedRulesExplanationTest.java
- ruta-docbook/src/docbook/tools.ruta.overview.xml
> [UIMA-6359] Ruta: parameter to add debug annotations to indexes

- ruta-core/src/main/java/org/apache/uima/ruta/action/AddAction.java
- ruta-core/src/main/java/org/apache/uima/ruta/action/RemoveAction.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/AddTest.java
> [UIMA-6346] Ruta Action ADD case FLOAT missing

- ruta-core/src/main/java/org/apache/uima/ruta/rule/WildCardRuleElement.java
- ruta-core/src/test/java/org/apache/uima/ruta/rule/WildCardInWindowTest.java
- ruta-eclipse-update-site/pom.xml
- ruta-parent/pom.xml
- Upgrade to UIMA Parent POM 14
- Upgrade to UIMA / uimaFIT SNAPSHOTs
> [UIMA-6337] Upgrade Ruta to UIMA 3.2.0 and uimaFIT 3.2.0

- example-projects/ruta-ep-example-extensions/pom.xml
- ruta-core/pom.xml
- ruta-core/src/main/java/org/apache/uima/ruta/engine/RutaTestUtils.java
- ruta-core/src/main/java/org/apache/uima/ruta/resource/MultiTreeWordList.java
- ruta-ep-addons/pom.xml
- ruta-ep-caseditor/pom.xml
- ruta-ep-core-ext/pom.xml
- ruta-ep-engine/pom.xml
- ruta-ep-engine/src/main/readme_bin/LICENSE
- ruta-ep-engine/src/main/readme_bin/NOTICE
- ruta-ep-ide-ui/pom.xml
- ruta-ep-ide/pom.xml
- ruta-ep-parent/pom.xml
- ruta-parent/pom.xml
- update version
- improve pom layout
- adapt notice and license in binaries
> [UIMA-6362] Ruta: update versions and notice in eclipse plugin bundles

- ruta-maven-plugin/src/main/java/org/apache/uima/ruta/maven/RutaGenerateDescriptorMojo.java
- Fix the resolution and collection metadata on the mojos so that they actually see all resolved artifacts ...
> [UIMA-6396] uimaFIT maven plugin mixes up test and compile scopes

- ruta-core/.gitignore
- ruta-core/src/main/java/org/apache/uima/ruta/RutaStream.java
- ruta-core/src/main/java/org/apache/uima/ruta/engine/RutaTestUtils.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/UnmarkTest.java
> UIMA-6406: Removing an annotation inside a BLOCK only takes effect outside the block

- ruta-core/src/main/java/org/apache/uima/ruta/rule/RutaRuleElement.java
- ruta-core/src/test/java/org/apache/uima/ruta/rule/quantifier/MinMaxQuantifierTest.java
- added test mentioned in issue
> UIMA-6404: Ruta: @ with quantifier ignores matches

- ruta-core/src/main/java/org/apache/uima/ruta/rule/AbstractRuleElement.java
- ruta-core/src/main/java/org/apache/uima/ruta/rule/RutaRule.java
- ruta-core/src/main/java/org/apache/uima/ruta/rule/RutaRuleElement.java
- ruta-core/src/test/java/org/apache/uima/ruta/expression/annotation/AnnotationLabelExpressionTest.java
> UIMA-6394: Ruta: label assignment in alternative match causes problems

- ruta-core/src/main/java/org/apache/uima/ruta/resource/MultiTreeWordList.java
- ruta-docbook/src/docbook/tools.ruta.howtos.xml
- ruta-docbook/src/docbook/tools.ruta.workbench.create_dictionaries.xml
- ruta-ep-addons/src/main/java/org/apache/uima/ruta/utils/twl/MultiTWLConverterHandler.java
- ruta-ep-addons/src/main/java/org/apache/uima/ruta/utils/twl/TWLConverterHandler.java
- ruta-ep-ide-ui/src/main/java/org/apache/uima/ruta/ide/ui/preferences/RutaBuilderPreferencePage.java
- ruta-ep-ide-ui/src/main/java/org/apache/uima/ruta/ide/ui/preferences/RutaPreferencesMessages.java
- ruta-ep-ide-ui/src/main/resources/org/apache/uima/ruta/ide/ui/preferences/RutaPreferencesMessages.properties
- ruta-ep-ide/src/main/java/org/apache/uima/ruta/ide/core/RutaCorePreferences.java
- ruta-ep-ide/src/main/java/org/apache/uima/ruta/ide/core/RutaPreferenceInitializer.java
- ruta-maven-plugin/src/it/wordlists/pom.xml
- ruta-maven-plugin/src/main/java/org/apache/uima/ruta/maven/RutaGenerateMTWLMojo.java
- ruta-maven-plugin/src/main/java/org/apache/uima/ruta/maven/RutaGenerateTWLMojo.java
- add option to select dictRemoveWS in eclipese plugin and maven plugin
> UIMA-6383: Ruta: TRIE - Wordlist entry not annotated

- ruta-core/src/main/java/org/apache/uima/ruta/action/TransferAction.java
- ruta-core/src/test/java/org/apache/uima/ruta/action/TransferTest.java
- log instead of thowing an exception
> UIMA-6408: Ruta: No type check of features in TRANSFER

- ruta-core/src/main/java/org/apache/uima/ruta/RutaStream.java
- ruta-core/src/test/java/org/apache/uima/ruta/EmptyDocumentTest.java
> UIMA-6411: Ruta: avoid creation of RutaBasics for bad annotations

- ruta-core/src/main/java/org/apache/uima/ruta/rule/AbstractRuleElement.java
- ruta-core/src/main/java/org/apache/uima/ruta/rule/ComposedRuleElement.java
- ruta-core/src/main/java/org/apache/uima/ruta/rule/RutaRuleElement.java
- ruta-core/src/test/java/org/apache/uima/ruta/ConjunctiveRuleElementTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/rule/ManualAnchoringTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/rule/RutaOptionalRuleElementTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/rule/SidestepInComposedTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/rule/quantifier/MinMaxQuantifierTest.java
> UIMA-6414: Ruta: missing match for optional after sidestep out of composed

- example-projects/ruta-ep-example-extensions/pom.xml
- example-projects/ruta-maven-example/pom.xml
- pom.xml
- ruta-basic-type/pom.xml
- ruta-core-ext/pom.xml
- ruta-core/pom.xml
- ruta-docbook/pom.xml
- ruta-eclipse-feature/pom.xml
- ruta-ep-addons/pom.xml
- ruta-ep-caseditor/pom.xml
- ruta-ep-core-ext/pom.xml
- ruta-ep-engine/pom.xml
- ruta-ep-ide-ui/pom.xml
- ruta-ep-ide/pom.xml
- ruta-ep-parent/pom.xml
- ruta-ep-textruler/pom.xml
- ruta-maven-archetype/pom.xml
- ruta-maven-plugin/pom.xml
- ruta-parent/pom.xml
- ruta-typesystem/pom.xml
* Update POMs to version 3.2.0-SNAPSHOT
* No particular test procedure
<sub><sup>Only dependencies under [approved licenses](http://www.apache.org/legal/resolved.html#category-a)
are allowed. LICENSE and NOTICE files in the respective modules where dependencies have been
added as well as in the project root have been updated.</sup></sub>
> No issue update version

- .github/PULL_REQUEST_TEMPLATE.md
- ruta-parent/pom.xml
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6426
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6433
- Apache UIMA SDK 3.2.0 -> 3.3.0
- Pull request template formatting 
* No specific test
<sub><sup>Only dependencies under [approved licenses](http://www.apache.org/legal/resolved.html#category-a)
are allowed. LICENSE and NOTICE files in the respective modules where dependencies have been
added as well as in the project root have been updated.</sup></sub>
> [UIMA-6426] Upgrade to UIMA Java SDK 3.3.0

- ruta-core/pom.xml
- ruta-core/src/main/java/org/apache/uima/ruta/RutaStream.java
- ruta-core/src/main/java/org/apache/uima/ruta/action/GatherAction.java
- ruta-core/src/main/java/org/apache/uima/ruta/action/MergeAction.java
- ruta-core/src/main/java/org/apache/uima/ruta/condition/ImplicitCondition.java
- ruta-ep-engine/pom.xml
- ruta-parent/pom.xml
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6447
- Commons Collections 4 -> 4.4
- Remove usages of Commons Collections 3 in the Ruta Code
> [UIMA-6447] Update dependencies (Ruta 3.2.0)

- .asf.yaml
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-XXXX
- Add branch protection rules and more settings
> [UIMA-6438] Add asf.yaml files to UIMA repos

- ruta-ep-ide-ui/src/main/java/org/apache/uima/ruta/ide/validator/LanguageCheckerVisitor.java
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6461
- Use `conditionName` instead of `cond`
> [UIMA-6461] Wrong argument to contains()

- ruta-eclipse-feature/pom.xml
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6462
- Prevent feature modules from being deployed
* Run "deploy" goal on a feature module and check that it has no effect
> [UIMA-6462] Avoid deploy broken checksum files for p2content.xml and artifacts.xml in feature modules

- ruta-parent/pom.xml
**JIRA Ticket:** https://issues.apache.org/jira/browse/UIMA-6463
- Add toolchain plugin
> [UIMA-6463] Use toolchains to ensure compatibility with Java 1.8

- Jenkinsfile
- ruta-parent/pom.xml
* Avoid triggering auto-staging as part of snapshot deployment
> [No Jira] Avoid triggering auto-staging as part of snapshot deployment

- example-projects/ruta-ep-example-extensions/pom.xml
- example-projects/ruta-maven-example/pom.xml
- pom.xml
- ruta-basic-type/pom.xml
- ruta-core-ext/pom.xml
- ruta-core/pom.xml
- ruta-docbook/pom.xml
- ruta-eclipse-feature/feature.xml
- ruta-eclipse-feature/pom.xml
- ruta-eclipse-update-site/category.xml
- ruta-eclipse-update-site/pom.xml
- ruta-ep-addons/pom.xml
- ruta-ep-caseditor/pom.xml
- ruta-ep-core-ext/pom.xml
- ruta-ep-engine/pom.xml
- ruta-ep-ide-ui/pom.xml
- ruta-ep-ide/pom.xml
- ruta-ep-parent/pom.xml
- ruta-ep-textruler/pom.xml
- ruta-maven-archetype/pom.xml
- ruta-maven-plugin/pom.xml
- ruta-parent/pom.xml
- ruta-typesystem/pom.xml
* Update version after release.
> [No Jira] Update version after release

- ruta-typesystem/pom.xml
- ruta-typesystem/src/main/java/org/apache/uima/ruta/type/spi/RutaTypeSystemDescriptionProvider.java
- Add missing OSGI package imports
- Use utility method from core in SPI
> Issue #100 - Enable type system discovery via SPI in OSGI

- ruta-core/src/main/java/org/apache/uima/ruta/engine/RutaEngine.java
- consider the extensions classloader, TCCL and then the local classloader in that order
> Issue #107 - Enable loading uimaFIT annotators and other classes through the TCCL

- ruta-ep-caseditor/src/main/java/org/apache/uima/ruta/caseditor/view/tree/AnnotationTreeViewPage.java
* fix clipboard
* ctrl c for selected tree nodes
> Issue #111: Support copy/paste clipboard for feature values in annotation browser view

- .github/PULL_REQUEST_TEMPLATE.md
- ruta-parent/pom.xml
- UIMA parent POM 16-SNAPSHOT -> 16
- Fix name of marker file enabling the changes report
> #104 - Upgrade dependencies

- ruta-ep-parent/pom.xml
- ruta-parent/pom.xml
> Issue #104: Upgrade dependencies

- ruta-parent/pom.xml
- uimaj 3.5.0-SNAPSHOT -> 3.5.0
> Issue #133: Update dependencies

- pom.xml
- ruta-parent/pom.xml
- Switch changelog generation approach
* Run dry-run release build and check `issuesFixed` folder
> Issue #147: Switch to GH-based changes generation

- ruta-eclipse-feature/feature.xml
- ruta-eclipse-update-site/category.xml
- Update update site URLs
* Try installing from a locally built update site into a fresh Eclipse
> Issue #155: UIMA Core plugins not found when installing Ruta

- ruta-maven-plugin/src/main/java/org/apache/uima/ruta/maven/RutaGenerateDescriptorMojo.java
- ruta-maven-plugin/src/main/java/org/apache/uima/ruta/maven/RutaGenerateMTWLMojo.java
- ruta-maven-plugin/src/main/java/org/apache/uima/ruta/maven/RutaGenerateTWLMojo.java
> Issue #157: Mark Maven Mojos as thread-safe

- ruta-core/src/main/antlr3/org/apache/uima/ruta/parser/RutaParser.g
- ruta-core/src/main/java/org/apache/uima/ruta/condition/ConditionFactory.java
- ruta-core/src/main/java/org/apache/uima/ruta/expression/ExpressionFactory.java
- ruta-core/src/main/java/org/apache/uima/ruta/expression/GenericComposedExpression.java
- ruta-core/src/main/java/org/apache/uima/ruta/utils/UIMAUtils.java
- ruta-core/src/main/java/org/apache/uima/ruta/verbalize/ExpressionVerbalizer.java
- ruta-core/src/test/java/org/apache/uima/ruta/expression/number/ComposedNumberExpressionTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/expression/number/NumberExpressionTest.java
- ruta-core/src/test/java/org/apache/uima/ruta/verbalizer/ExpressionVerbalizerTest.java
* avoid disambiguation problems with generic expression
* ...
> Issue #159: Assignment of composed number expression is broken

- ruta-core/src/test/java/org/apache/uima/ruta/rule/WildCard2Test.java
> Issue #161: Right to left wildcard matches too much

- example-projects/ruta-maven-example/pom.xml
- pom.xml
- ruta-core-ext/pom.xml
- ruta-core/pom.xml
- ruta-eclipse-update-site/pom.xml
- ruta-ep-addons/pom.xml
- ruta-ep-caseditor/pom.xml
- ruta-ep-core-ext/pom.xml
- ruta-ep-engine/pom.xml
- ruta-ep-ide-ui/pom.xml
- ruta-ep-ide/pom.xml
- ruta-ep-parent/pom.xml
- ruta-ep-textruler/pom.xml
- ruta-maven-archetype/pom.xml
- ruta-maven-plugin/pom.xml
- ruta-parent/pom.xml
> no issue: cleanup

- RELEASE_NOTES.md
- example-projects/ruta-ep-example-extensions/pom.xml
- example-projects/ruta-maven-example/pom.xml
- pom.xml
- ruta-core-ext/pom.xml
- ruta-core/pom.xml
- ruta-documentation/pom.xml
- ruta-eclipse-feature/feature.xml
- ruta-eclipse-feature/pom.xml
- ruta-eclipse-update-site/category.xml
- ruta-eclipse-update-site/pom.xml
- ruta-ep-addons/pom.xml
- ruta-ep-caseditor/pom.xml
- ruta-ep-core-ext/pom.xml
- ruta-ep-engine/pom.xml
- ruta-ep-ide-ui/pom.xml
- ruta-ep-ide/pom.xml
- ruta-ep-parent/pom.xml
- ruta-ep-textruler/pom.xml
- ruta-maven-archetype/pom.xml
- ruta-maven-plugin/pom.xml
- ruta-parent/pom.xml
- Update RELEASE_NOTES
- Update reference versions for API compatibility checks and changelog generation
> Issue #165: Apache UIMA Ruta 3.4.1

- RELEASE_NOTES.md
- ruta-parent/pom.xml
* No issue merge 3.4.x after release
> No issue merge 3.4.x after release

- ruta-ep-caseditor/src/main/java/org/apache/uima/ruta/caseditor/view/tree/AnnotationTreeViewPage.java
- cleanup control and listener when page is created twice
* see issue description
> Issue #173: Potential memory leak in Annotation Browser View

- ruta-parent/pom.xml
> Issue #179: Remove toolchains

- ruta-parent/pom.xml
- spring 5.3.3.0 -> 5.3.39
- junit 5.10.1 -> 5.11.3
- assertj 3.24.2 -> 3.26.3
- commons-text 1.11.0 -> 1.12.0
- commons-lang3 3.14.0 -> 3.17.9
- commons-io 2.15.1 -> 2.17.0
- commons-logging 1.3.0 -> 1.3.4
- asciidoctor-plugin 2.2.4 -> 3.0.0
- asciidoctorj 2.5.10 -> 3.0.0
- asciidoctorj-pdf 2.3.9 -> 2.3.19
> Issue #176 - Upgrade dependencies

- ruta-eclipse-feature/feature.xml
- uima java sdk 3.5.0 -> 3.6.0 (in Eclipse feature)
* Build from source ZIP (apparently)
> Issue #176: Upgrade dependencies

- .asf.yaml
* Un-require status checkes
* Try merging release branch into main branch
> No issue: Unrequire status checks

- ruta-core/src/main/java/org/apache/uima/ruta/engine/RutaEngine.java
- Pass a null TS to avoid scanning
> Issue #189: Avoid type system scanning when initializing uimaFIT annotators from a Ruta script
